// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int greater = 0;
		int lower = 0;
		double currentRandom = 0;
		double ratio ;
		for (int i = 0; i < n; i++) {
			currentRandom = Math.random();
			if (currentRandom <= 0.5) {
				lower++;
			}  
			else{
			greater++;
			}
		}
		System.out.println("> 0.5: " + greater);
		System.out.println("<= 0.5: "+ lower);
			if (greater >0 && lower >0){
				ratio = greater / lower;
				System.out.println("Ratio:" + ratio);
		}

		}
	}

